name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:alpine

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test